# Generated by Django 3.2.9 on 2021-12-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0002_rename_basket_orders_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='number',
        ),
    ]
