# Generated by Django 3.2.9 on 2021-12-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0003_remove_orders_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='slag',
            new_name='slug',
        ),
    ]
