# Generated by Django 3.2.9 on 2021-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0004_rename_slag_goods_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='session_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
