# Generated by Django 3.2.9 on 2021-12-17 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0006_auto_20211218_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easytrade.measure'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easytrade.categories'),
        ),
    ]
