# Generated by Django 3.2.9 on 2021-12-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0009_goodtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_type',
        ),
    ]
