# Generated by Django 3.2.9 on 2021-12-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0011_goods_goods_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(),
        ),
    ]
