# Generated by Django 3.2.9 on 2022-01-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0019_alter_categories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='uploads/supercategory/')),
            ],
        ),
    ]
