# Generated by Django 3.2.9 on 2022-01-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0021_categories_super_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskets',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='baskets',
            name='description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
