# Generated by Django 3.2.9 on 2022-01-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0022_auto_20220108_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='baskets',
            name='telephone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='baskets',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
