# Generated by Django 3.2.9 on 2021-12-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='basket',
            new_name='number',
        ),
    ]
