# Generated by Django 3.2.9 on 2021-12-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0005_orders_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='UID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='good_ID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='goods',
            name='search_queries',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='goods',
            name='search_queries_ukr',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='easytrade.categories'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
    ]
