# Generated by Django 3.2.9 on 2021-12-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0007_auto_20211218_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='measure_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='name',
        ),
    ]
