# Generated by Django 3.2.9 on 2021-12-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0008_auto_20211218_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
