# Generated by Django 3.2.9 on 2021-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0012_alter_goods_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товари'},
        ),
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
