# Generated by Django 3.2.9 on 2021-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0013_auto_20211228_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='slug',
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
