# Generated by Django 3.2.9 on 2021-12-28 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0015_alter_categories_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='slug',
        ),
    ]
