# Generated by Django 3.2.9 on 2022-01-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0020_supercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='super_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easytrade.supercategory'),
        ),
    ]
