# Generated by Django 4.0.2 on 2022-02-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0023_auto_20220108_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='end_price',
            field=models.FloatField(default=0, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easytrade.categories', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='В популярні'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Публікувати'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_trend',
            field=models.BooleanField(default=False, verbose_name='В тренди'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='easytrade.measure', verbose_name='Одиниці виміру'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='photo',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='Фото товару'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='"Чиста" ціна'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='search_queries',
            field=models.TextField(default='', verbose_name='Пошукові запити'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='search_queries_ukr',
            field=models.TextField(default='', verbose_name='Пошукові запити(укр)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
