# Generated by Django 4.0.2 on 2022-02-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easytrade', '0024_goods_end_price_alter_goods_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='articul',
            field=models.CharField(default='0', max_length=50, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='Артикул старий'),
        ),
    ]
